# Generated by Django 5.2.8 on 2025-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analytics",
            old_name="shortener",
            new_name="shortener_id",
        ),
        migrations.AddField(
            model_name="analytics",
            name="base62_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
