# Generated by Django 5.2.7 on 2025-10-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='shortened_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
