# Generated by Django 5.2.8 on 2025-11-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_analytics"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Analytics",
        ),
    ]
